
spring.application.name=myfirstspringproject


management.endpoints.web.exposure.include=health,info
management.info.env.enabled = true


info.app.main =My First App
info.app.description = Welcome to our app 
info.app.version = 1.0.0